[package]
name = "deploy_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
serde_json = "1.0"
dotenv = "0.15.0"
ethers = { version = "2.0", features = ["rustls"] }
ethers-solc = "1.0.2"
eyre = "0.6"
tokio = { version = "1", features = ["full"] }
serde = "1.0.149"