[package]
name = "kaviar"
version = "1.0.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
serde = "1.0"
serde_json = "1.0"
base64 = "0.13"
dotenv = "0.15.0"
ethers = { version = "2.0", features = ["rustls"] }
ethers-solc = "1.0.2"
eyre = "0.6"
tokio = { version = "1", features = ["full"] }